language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: GFqpbuP0FumOoerR4x10KMwpsAnaYMcWgF35IcIyZEX1/LIsvFMEJmhxqPkQcHbG2lE6D1TJfa6onTI2loUf1nPHLWphcQ8KkoNVlCzEWBHYkJt8E75X2pyT1TfAi/i35Ms4OEcSO3w3ZUJZTR2glib4MVqDcjPsSErr9a9sObioXvoEYK0JF+heRSBhdhzFxAhtI50CgD0QZrMmou2pStK8V4gQhNQ8xloWyE81igKgkv+f2ai0O9Pj3PQAF2WDtP69bgzE7BG3uu1MFuHm5ZN7KXyRNELq5eZtildIFz0kbnDJiE7qr+UzpLpilMP7TS4geZAQPSC7pqxG1tSEUjx56AGtwecLSxJvLEFlFu9vSwfTFvxr1uyZKFxuY5/19ie7A/MdMZc2wgD2DBSszAVMB9YFXDhXJRFzYU9D2/5XIcDzqZQ4+/Ra5o7Bh8RZGcohR1D0maS1RRVB7PxjIzBHUYsejsWmBw0Ay8Z61MelK+gQkgXrVITNutPe3nKLx6bbtDyehrA4mYbkqIRQSvvQDv2OLd1EoXFArFET0Pqq0+0uAVfIDxFL6Y5L2Lo25MowqpCnKIT10PbjuM4/VOMCHFbMVX7bZhRk6zjfHKrkQxcHjQUFtR9fpCiz/TSL0GdczEdr0vpPRjt/KWOWBRhDnNY6+Brth84RoqU7k70=
  app: Marwan-Noteful-v3
  on:
    repo: thinkful-ei27/Marwan-Noteful-v3
